### ISSUE TITLE
Fix Bounding Box Visualization for SynthDet ipython notebook

### ISSUE THREAD

**Issue by sanjayuconn** [Unity-Technologies/datasetinsights#12]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-39d17783049a> in <module>
     44     return estimator
     45 
---> 46 synth_estimator = load_estimator(SYNTH_ESTIMATOR_CLOUD_PATH)
     47 real_estimator = load_estimator(REAL_ESTIMATOR_CLOUD_PATH)

<ipython-input-4-39d17783049a> in load_estimator(checkpoint)
     40     writer = SummaryWriter()
     41     checkpointer = create_checkpointer(logdir=writer.logdir, config=config)
---> 42     estimator = Estimator.create(config.estimator, config=config, writer=writer, device=device, checkpointer=checkpointer)
     43 
     44     return estimator

/datasetinsights/datasetinsights/estimators/base.py in create(name, **kwargs)
     30         """
     31         estimators_cls = Estimator.find(name)
---> 32         return estimators_cls(**kwargs)
     33 
     34     @staticmethod

TypeError: __init__() missing 1 required keyword-only argument: 'kfp_writer'

**Comment by adason** [comment]
This notebook is currently in draft. All officially supported notebook have been fixed in https://github.com/Unity-Technologies/datasetinsights/pull/66
