### ISSUE TITLE
Cleanup Kubeflow Pipeline PVC after training completes

### ISSUE THREAD

**Issue by adason** [Unity-Technologies/datasetinsights#120]
**Why you need this feature:**
Since we are running kubeflow pipeline as independent runs without any intention to keep data around for next runs, we should cleanup these PVC after the job complets.

**Comment by Saurav-D** [comment]
https://github.com/kubeflow/pipelines/issues/1779

**Comment by adason** [comment]
Since datasetinsights does not contain model training and evaluation code, I am closing this issue now.
