### ISSUE TITLE
Error with pip install datasetinsights Windows 10, Python 3.8.6

### ISSUE THREAD

**Issue by jamesheatonrdm** [Unity-Technologies/datasetinsights#136]
**Describe the Bug:**
Cannot install datasetinsights using pip install. Error occurs, seemingly comes from functoolz.py. Cannot change python file associated with error as it is placed in Appdata\Local\Temp and is removed one error occurs.

**How to Reproduce?**
pip install datasetinsights

**What did you expect to happen:**
package would install without issues

**Console logs / stack traces**
```    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jheaton\documents\ml\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jheaton\\AppData\\Local\\Temp\\pip-install-enmyh5vb\\toolz_c453f12303af4995ad3bf8f64e4137fb\\setu
p.py'"'"'; __file__='"'"'C:\\Users\\jheaton\\AppData\\Local\\Temp\\pip-install-enmyh5vb\\toolz_c453f12303af4995ad3bf8f64e4137fb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"
'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jheaton\AppData\Local\Temp\pip-pip-egg-info-uyq52yk3'
         cwd: C:\Users\jheaton\AppData\Local\Temp\pip-install-enmyh5vb\toolz_c453f12303af4995ad3bf8f64e4137fb\
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jheaton\AppData\Local\Temp\pip-install-enmyh5vb\toolz_c453f12303af4995ad3bf8f64e4137fb\setup.py", line 5, in <module>
        import toolz
      File "C:\Users\jheaton\AppData\Local\Temp\pip-install-enmyh5vb\toolz_c453f12303af4995ad3bf8f64e4137fb\toolz\__init__.py", line 3, in <module>
        from .functoolz import *
      File "C:\Users\jheaton\AppData\Local\Temp\pip-install-enmyh5vb\toolz_c453f12303af4995ad3bf8f64e4137fb\toolz\functoolz.py", line 501
        f.__name__ for f in reversed((self.first,) + self.funcs),
        ^
    SyntaxError: Generator expression must be parenthesized
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Anything else you would like to add:**
Have already attempted pip install --upgrade setuptools with no success

**Environment:**

- OS + version: Microsoft Windows 10.0.18363 Build 18363
- datasetinsights version 0.2.3
- _Environment_: Python 3.8.6

**Comment by jamesheatonrdm** [comment]
Glad to see there is support for this!!!

**Comment by adason** [comment]
This might be related to https://github.com/Unity-Technologies/datasetinsights/issues/48 issue. The windows virtual environment was not fully tested due to this issue. We will revisit this once the model training dependencies (pytorch, tensorflow,...) of the repos is removed.

**Comment by 86sanj** [comment]
Current repo does not hold any deep learning libraries after https://github.com/Unity-Technologies/datasetinsights/issues/143 release. So closing this issue. 
- Testing:  Able to install datasetinsights 1.0 on window machines successfully.
