### ISSUE TITLE
Scripts to convert perception output to COCO format

### ISSUE THREAD

**Issue by adason** [Unity-Technologies/datasetinsights#159]
**Why you need this feature:**
COCO format is wildly adopted for a few CV tasks

**Describe the solution you'd like:**
I would like to have a script that can easily convert perception output to COCO format for all supported tasks. These tasks are

- [ ] 2D object detection https://github.com/Unity-Technologies/datasetinsights/issues/171
- [ ] keypoints
- [ ] instance segmentation
- [ ] Panoptic Segmentation

**Comment by adason** [comment]
We should consider decoupling this task. I specifically carved out the 2D bounding box task https://github.com/Unity-Technologies/datasetinsights/issues/171 and updated the issue description.

**Comment by romerocesar** [comment]
My vote is to add a submodule called `converters` with a standalone script that is used like:
`unity2coco task source dest`
and then a similar pattern can be used to support other formats (e.g. kitti) in the future

**Comment by orangeRobot990** [comment]
any updates on this ?
I am very interested in this feature

**Comment by salehe-ee** [comment]
@orangeRobot990 we already support converting Perception outputs to COCO standard. Please see [this instruction](https://github.com/Unity-Technologies/datasetinsights#convert-datasets).

**Comment by Robotatron** [comment]
> @orangeRobot990 we already support converting Perception outputs to COCO standard. Please see [this instruction](https://github.com/Unity-Technologies/datasetinsights#convert-datasets).

It seems no instance segmentation support. 
Any plans implementing it in the near future?
