### ISSUE TITLE
Remove unwanted import to break circular dependency

### ISSUE THREAD

**Issue by adason** [Unity-Technologies/datasetinsights#43]
/kind bug

**Describe the Bug:**

Remove import `Downloader` and `download_manifest` in `datasetinsights/datasets/synthetic.py` to break circular dependency. These two imports are originally used to download data for unity simulation and called in the `__init__` method, but they are no longer required after recent refactoring.

**Comment by Saurav-D** [comment]
@sanjayuconn is this fixed?

**Comment by sanjayuconn** [comment]
@Saurav-D: This https://github.com/Unity-Technologies/datasetinsights/pull/30 PR covers the fix of this issue. We can close after merging.

**Comment by sanjayuconn** [comment]
Issue has resolved: https://github.com/Unity-Technologies/datasetinsights/pull/30
