### ISSUE TITLE
Add instructions how to run dataset evaluations using docker

### ISSUE THREAD

**Issue by adason** [Unity-Technologies/datasetinsights#83]
**Why you need this feature:**

Provide instructions how users can run dataset evaluation by running download/train/evaluate commands using `docker run` command on a localhost machine. This tutorial will allow users to generate a synthetic dataset locally using Unity preview mode and use this dataset to kick off dataset evaluation.  

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by 86sanj** [comment]
We don't support evaluation in the current repo after https://github.com/Unity-Technologies/datasetinsights/issues/143 release. So closing this issue.
