### ISSUE TITLE
Metrics file exists error

### ISSUE THREAD

**Issue by BlairLee** [Unity-Technologies/datasetinsights#99]
**Describe the Bug:**
After the training process is done, it would through a FileExistsError. 

**How to Reproduce?**
You can use these settings to reproduce the error:
<img width="713" alt="Screen Shot 2020-09-18 at 12 14 57 PM" src="https://user-images.githubusercontent.com/22140633/93636371-a964d100-f9a8-11ea-919b-7f70250bbd06.png">

**What did you expect to happen:**
Maybe kfp_writer writes metrics twice at the end of the training epoch.

**Console logs / stack traces**
```
FileExistsError: [Errno 17] File exists: '/datasetinsights/metrics/20200918-030117'
```

**Anything else you would like to add:**
It's not a critical bug, but we need to take a look at this.

**Environment:**

- OS + version: [e.g. Ubuntu 20.04.1 LTS]
- datasetinsights version
- _Environment_: (which example environment you used to reproduce the error)
- Other environment settings

**Comment by 86sanj** [comment]
We don't support metric in current repo after https://github.com/Unity-Technologies/datasetinsights/issues/143 release. So closing this issue.
